# voltrix
# a sweet, maximalist colorscheme for alacritty
# ( allomyrina volbot <volbot.tech@gmail.com> )

# Normal colors
[colors.normal]
black   = '#090609'
red     = '#de4779'
green   = '#9cdd3c'
yellow  = '#ddc43c'
blue    = '#3c74dd'
magenta = '#a73cdd'
cyan    = '#3cddd7'
white   = '#d9d9d9'

# Bright colors
[colors.bright]
black   = '#8c8c8c'
red     = '#e87da1'
green   = '#bde87d'
yellow  = '#e8d87d'
blue    = '#7da3e8'
magenta = '#c47de8'
cyan    = '#7de8e4'
white   = '#fcfcfc'

[colors.primary] #default
background = '#090609'
foreground = '#fcfcfc'

[colors.cursor]
cursor  = '#009845'
text    = '#fcfcfc'

[colors.selection]
background  = '#68228B'
text        = '#fcfcfc'
