# voltrix
# a sweet, maximalist colorscheme for alacritty
# by allomyrina volbot <volbot333@gmail.com>

# Normal colors
[colors.normal]
black   = '#090609'
red     = '#da4e7d'
green   = '#8bd225'
yellow  = '#f4d661'
blue    = '#76a3e4'
magenta = '#c37ffc'
cyan    = '#6cb6ab'
white   = '#e5deee'

# Bright colors
[colors.bright]
black   = '#6b6b6b'
red     = '#f5a9b8'
green   = '#bfd86d'
yellow  = '#f5e498'
blue    = '#87c3ff'
magenta = '#cc9bfc'
cyan    = '#acd4cd'
white   = '#fdfcfd'

[colors.primary] #default
background = '#090609' #[colors.normal.black]
foreground = '#fdfcfd' #[colors.bright.white]

[colors.cursor]
cursor  = '#009845' # green from box logo
text    = '#fdfcfd' #[colors.bright.white]

[colors.selection]
background  = '#662a90' # purple from box logo
text        = '#fdfcfd' #[colors.bright.white]

