# colors
foreground #ffffff
background #090609

# black
color0  #090609
color8  #776077
# red 
color1  #de4779
color9  #e6829b
# green
color2  #c4de47
color10 #d2e672
# yellow
color3  #deac47
color11 #e6c072
# blue
color4  #4779de
color12 #7298e6
# magenta
color5  #ac47de
color13 #c072e6
# cyan
color6  #47deac
color14 #72e6c0
# white
color7  #e9dde9
color15 #ffffff
