# vim:ft=kitty

## name:     base16 voltrix
## author:   allomyrina volbot (http://volbot.org)
## license:  MIT
## upstream: https://github.com/tinted-theming/tinted-terminal
## blurb:    

# Scheme name: base16 voltrix
# Scheme author: allomyrina volbot (http://volbot.org)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

# The basic colors
background #0b0910
foreground #ffffff
selection_background #b0adb8
selection_foreground #ffffff

# Cursor colors
cursor #ffffff
cursor_text_color #0b0910

# URL underline color when hovering with mouse
url_color #928aa8

# Kitty window border colors
active_border_color #b0adb8
inactive_border_color #373049

# OS Window titlebar colors
wayland_titlebar_color #0b0910
macos_titlebar_color #0b0910

# Tab bar colors
active_tab_background #0b0910
active_tab_foreground #ffffff
inactive_tab_background #373049
inactive_tab_foreground #928aa8
tab_bar_background #373049

# The 16 terminal colors
# normal
color0 #0b0910
color1 #de4779
color2 #4779de
color3 #de47c5
color4 #79de47
color5 #deac47
color6 #47deac
color7 #ffffff

# bright
color8 #3b344e
color9 #de4779
color10 #4779de
color11 #de47c5
color12 #79de47
color13 #deac47
color14 #47deac
color15 #473e5f

# extended base16 colors
color16 #ac47de
color17 #de4779
color18 #373049
color19 #3b344e
color20 #928aa8
color21 #ffffff
