# tinted-foot
# Scheme name: voltrix
# Scheme author: allomyrina volbot (http://volbot.org)
# Template author: Tinted Theming (https://github.com/tinted-theming)

[colors]
foreground=ffffff
background=0b0910
regular0=373049 # black
regular1=de4779 # red
regular2=4779de # green
regular3=de47c5 # yellow
regular4=79de47 # blue
regular5=deac47 # magenta
regular6=de4779 # cyan
regular7=ffffff # white
bright0=3b344e # bright black
bright1=de4779 # bright red
bright2=4779de # bright green
bright3=de47c5 # bright yellow
bright4=79de47 # bright blue
bright5=deac47 # bright magenta
bright6=de4779 # bright cyan
bright7=473e5f # bright white
16=ac47de
17=47deac
18=373049
19=3b344e
20=928aa8
21=ffffff
