# base16 voltrix
# Scheme author: allomyrina volbot (http://volbot.org)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-termihal)

[colors]
background = "#090910"
foreground = "#ffffff"

cursor_bg = "#ffffff"
cursor_border = "#ffffff"
cursor_fg = "#090910"

selection_bg = "#ffffff"
selection_fg = "#3e3e5f"

ansi = [
  "#090910",
  "#de4779",
  "#4779de",
  "#de47c5",
  "#79de47",
  "#deac47",
  "#de4779",
  "#ffffff"
]
brights = [
  "#3e3e5f",
  "#de4779",
  "#4779de",
  "#de47c5",
  "#79de47",
  "#deac47",
  "#de4779",
  "#cd255d"
]

[colors.indexed]
16 = "#ac47de"
17 = "#47deac"
18 = "#303049"
19 = "#3e3e5f"
20 = "#8a8aa8"
21 = "#ffffff"
