# Rio Terminal base16 color theme (https://github.com/tinted-theming)
# Color scheme: voltrix by allomyrina volbot (http://volbot.org)

[colors]
selection-background = '#3b344e' # base02
selection-foreground = '#ffffff' # base05

cursor         = '#ffffff' # base05
tabs           = '#373049' # base01
tabs-active    = '#3b344e' # base02

background     = '#0b0910' # base00
foreground     = '#ffffff' # base05
black          = '#373049' # base01
red            = '#de4779' # base08
yellow         = '#de47c5' # base0A
green          = '#4779de' # base0B
cyan           = '#47deac' # base0C
blue           = '#79de47' # base0D
magenta        = '#deac47' # base0E
white          = '#ffffff' # base06

dim-foreground   = '#ffffff' # base05
dim-black        = '#373049' # base01
dim-red          = '#de4779' # base08
dim-yellow       = '#de47c5' # base0A
dim-green        = '#4779de' # base0B
dim-cyan         = '#47deac' # base0C
dim-blue         = '#79de47' # base0D
dim-magenta      = '#deac47' # base0E
dim-white        = '#928aa8' # base04

light-foreground = '#ffffff' # base05
light-black      = '#3b344e' # base02
light-red        = '#de4779' # base08
light-yellow     = '#de47c5' # base0A
light-green      = '#4779de' # base0B
light-cyan       = '#47deac' # base0C
light-blue       = '#79de47' # base0D
light-magenta    = '#deac47' # base0E
light-white      = '#473e5f' # base07
